lrange1 = list(range(5))
lrange2 = tuple(range(5))
lrange3 = list(range(0, 4))
lrange4 = list(range(2, 6, 2))
lrange5 = list(range(4, 0, -1))
print(lrange1)
print(lrange2)
print(lrange3)
print(lrange4)
print(lrange5)
